version: "3.5"
services:
    postgres:
      image: postgres:11.3-alpine
      container_name: ${POSTGRES_CONTAINER_NAME}
      env_file: .env
      ports:
        - ${POSTGRES_EXT_PORT}:5432
      command: postgres -c logging_collector=on -c log_rotation_age=1440  -c log_truncate_on_rotation=true -c log_file_mode=0777 -c log_destination=stderr -c log_directory=./logs -c client_min_messages=notice -c log_min_messages=warning -c log_min_duration_statement=-1 -c log_statement=all  -c log_connections=0
      volumes:
        - "${POSTGRES_DIR}:/var/lib/postgresql/data"