version: "3.5"
services:
    postgres:
      image: postgres:11.3-alpine
      container_name: ${POSTGRES_CONTAINER_NAME}
      env_file: .env
      ports:
        - ${POSTGRES_EXT_PORT}:5432
      volumes:
        - "${POSTGRES_DIR}:/var/lib/postgresql/data"
        - "./sql:/docker-entrypoint-initdb.d"